version: 0.1.{build}

os:
  - osx

language: node_js
node_js:
  - "8"

cache: yarn

install:
  - yarn

script:
  - node --version
  - npm --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist-mac ; fi
