const types = {
    SEARCH: 'SEARCH',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    DIALOG_OPEN: 'DIALOG_OPEN',
    DIALOG_OK: 'DIALOG_CONFIRM',
    DIALOG_CANCEL: 'DIALOG_CANCEL',
    DIALOG_CLOSE: 'DIALOG_CLOSE',
    CREATE_ITEM: 'CREATE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    SET_ACTIVE_ITEM: 'SET_ACTIVE_ITEM',
    UNSET_ACTIVE_ITEM: 'UNSET_ACTIVE_ITEM',
    PUSH: 'PUSH',
    REPLACE: 'REPLACE',
    GO_BACK: 'GO_BACK',
    LOCK: 'LOCK',
    UNLOCK: 'UNLOCK',
    CREATE_STORE: 'CREATE_STORE',
    UPDATE_STORE_FILE: 'UPDATE_STORE_FILE'
};

export default types;
